//-----------------------------------------------------------------------------
//
//	This code was generated by a ResourceWrapper.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
//
//	Changes to this file may cause incorrect behavior and will be lost if
//	the code is regenerated.
//
//-----------------------------------------------------------------------------

namespace Fusion {
	using System;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated.
	// To add or remove a member, edit your .ResX file then rerun MsBuild,
	// or rebuild your VS project.
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal static class Resource {

		private static global::System.Resources.ResourceManager resourceManager;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if(resourceManager == null) {
					resourceManager = new global::System.Resources.ResourceManager("Fusion.Resource", typeof(Resource).Assembly);
				}
				return resourceManager;
			}
		}

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture { get; set; }

		/// <summary>
		/// Looks up a localized string similar to Bad format of number: '{0}' at {1}.
		/// </summary>
 		public static string BadNumberFormat(string number, string position) {
			return string.Format(Culture, ResourceManager.GetString("BadNumberFormat", Culture), number, position);
		}

		/// <summary>
		/// Looks up a localized string similar to "{" expected instead of {0} at {1}.
		/// </summary>
 		public static string BeginExpected(string token, string position) {
			return string.Format(Culture, ResourceManager.GetString("BeginExpected", Culture), token, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Compiled file get changed between passes..
		/// </summary>
 		internal static string FileChanged {
			get { return ResourceManager.GetString("FileChanged", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to Identifier is expected instead of {0} at {1}.
		/// </summary>
 		public static string IdentifierExpected(string text, string position) {
			return string.Format(Culture, ResourceManager.GetString("IdentifierExpected", Culture), text, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Missing file name for include at {0}.
		/// </summary>
 		public static string IncludeFileMissing(string position) {
			return string.Format(Culture, ResourceManager.GetString("IncludeFileMissing", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Include file "{0}" not found at {1}.
		/// </summary>
 		public static string IncludeFileNotFound(string file, string position) {
			return string.Format(Culture, ResourceManager.GetString("IncludeFileNotFound", Culture), file, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Condition is incomplete value. Only aready defined labes can be used in condition at {0}.
		/// </summary>
 		public static string IncompleteCondition(string position) {
			return string.Format(Culture, ResourceManager.GetString("IncompleteCondition", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Incomclusive error message at {0}.
		/// </summary>
 		public static string IncompleteError(string position) {
			return string.Format(Culture, ResourceManager.GetString("IncompleteError", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Attempt to write too big number ({0}) to the output at offset {1}. The value replaced with 0xFF.
		/// </summary>
 		public static string IncorrectNumber(int value, long offset) {
			return string.Format(Culture, ResourceManager.GetString("IncorrectNumber", Culture), value, offset);
		}

		/// <summary>
		/// Looks up a localized string similar to Incorrect value of type {0} is written to the output at offset {1}. The value replaced with 0xFF.
		/// </summary>
 		public static string IncorrectValue(string type, long offset) {
			return string.Format(Culture, ResourceManager.GetString("IncorrectValue", Culture), type, offset);
		}

		/// <summary>
		/// Looks up a localized string similar to Internal assember error..
		/// </summary>
 		internal static string InternalError {
			get { return ResourceManager.GetString("InternalError", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to {0} is expected instead of {1} at {2}.
		/// </summary>
 		public static string ItemExpected(string expected, string actual, string position) {
			return string.Format(Culture, ResourceManager.GetString("ItemExpected", Culture), expected, actual, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Label {0} redefined in macro {1} at {2}.
		/// </summary>
 		public static string LabelRedefined(string label, string macro, string position) {
			return string.Format(Culture, ResourceManager.GetString("LabelRedefined", Culture), label, macro, position);
		}

		/// <summary>
		/// Looks up a localized string similar to macro or include expected at {0}.
		/// </summary>
 		public static string MacroExpected(string position) {
			return string.Format(Culture, ResourceManager.GetString("MacroExpected", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Macro name expected instead of {0} at {1}.
		/// </summary>
 		public static string MacroNameExpected(string text, string position) {
			return string.Format(Culture, ResourceManager.GetString("MacroNameExpected", Culture), text, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Macro {0} redefined at {1}.
		/// </summary>
 		public static string MacroNameRedefinition(string name, string position) {
			return string.Format(Culture, ResourceManager.GetString("MacroNameRedefinition", Culture), name, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Macro "main" is missing..
		/// </summary>
 		internal static string MainMissing {
			get { return ResourceManager.GetString("MainMissing", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to Macro main should not has any parameters..
		/// </summary>
 		internal static string MainPararameters {
			get { return ResourceManager.GetString("MainPararameters", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to File included more then once: "{0}".
		/// </summary>
 		public static string MultipleInclusions(string path) {
			return string.Format(Culture, ResourceManager.GetString("MultipleInclusions", Culture), path);
		}

		/// <summary>
		/// Looks up a localized string similar to Single number value expected at {0}.
		/// </summary>
 		public static string NumberValueExpected(string position) {
			return string.Format(Culture, ResourceManager.GetString("NumberValueExpected", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Name of parameter can not be a keyword {0} at {1}.
		/// </summary>
 		public static string ParameterKeyword(string keyword, string position) {
			return string.Format(Culture, ResourceManager.GetString("ParameterKeyword", Culture), keyword, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Macro {0} already contins parameter {1} at {2}.
		/// </summary>
 		public static string ParameterRedefinition(string macro, string parameter, string position) {
			return string.Format(Culture, ResourceManager.GetString("ParameterRedefinition", Culture), macro, parameter, position);
		}

		/// <summary>
		/// Looks up a localized string similar to {0} ({1}).
		/// </summary>
 		public static string PositionText(string file, int line) {
			return string.Format(Culture, ResourceManager.GetString("PositionText", Culture), file, line);
		}

		/// <summary>
		/// Looks up a localized string similar to Identifier, literal, "(", or keyword.
		/// </summary>
 		internal static string PrimaryItem {
			get { return ResourceManager.GetString("PrimaryItem", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to Number or string value expected at {0}.
		/// </summary>
 		public static string StringOrNumberValueExpected(string position) {
			return string.Format(Culture, ResourceManager.GetString("StringOrNumberValueExpected", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to String value expected at {0}.
		/// </summary>
 		public static string StringValueExpected(string position) {
			return string.Format(Culture, ResourceManager.GetString("StringValueExpected", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Undefined macro {0} at {1}.
		/// </summary>
 		public static string UndefinedMacro(string name, string poisition) {
			return string.Format(Culture, ResourceManager.GetString("UndefinedMacro", Culture), name, poisition);
		}

		/// <summary>
		/// Looks up a localized string similar to Unexpected char '{0}' (0x{1:X}) in {2}.
		/// </summary>
 		public static string UnexpectedChar(char c, int value, string position) {
			return string.Format(Culture, ResourceManager.GetString("UnexpectedChar", Culture), c, value, position);
		}

		/// <summary>
		/// Looks up a localized string similar to Unexpected end of file at {0}.
		/// </summary>
 		public static string UnexpectedEOF(string position) {
			return string.Format(Culture, ResourceManager.GetString("UnexpectedEOF", Culture), position);
		}

		/// <summary>
		/// Looks up a localized string similar to Usage: fusion <InputFileName.asm> <OutputFileName.bin>.
		/// </summary>
 		internal static string Usage {
			get { return ResourceManager.GetString("Usage", Culture); }
		}
	}
}
