//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///macro r0 { 0 }
        ///macro r1 { 1 }
        ///
        ///macro a0 { 0 }
        ///macro a1 { 1 }
        ///
        ///macro validateRegister r {
        ///	if(!(r &lt;= r0 &amp;&amp; r &lt;= r7)) {
        ///		error &quot;invalid register&quot;
        ///	}
        ///}
        ///
        ///macro validateAddress a {
        ///	if(!(a &lt;= a0 &amp;&amp; a &lt;= a3)) {
        ///		error &quot;invalid address register&quot;
        ///	}
        ///}
        ///
        ///macro validateByte b {
        ///	if(!(0 &lt;= b &amp;&amp; b &lt;= 0xFF)) {
        ///		error &quot;invalid byte&quot;
        ///	}
        ///}
        ///
        ///macro dw value {
        ///	value &amp; oxFF
        ///	value &gt;&gt; 8
        ///}
        ///
        ///macro dwArray count {
        ///	if(0 &lt; count) {
        ///		dw 0
        ///		dwArray count - 1
        ///	}
        ///}
        ///
        ///;;;;;;;;;;;;;;;;;;;;;;;;;;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblerCompileFirstPassTest {
            get {
                return ResourceManager.GetString("AssemblerCompileFirstPassTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssemblerCompileSecondPassTest {
            get {
                return ResourceManager.GetString("AssemblerCompileSecondPassTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; hello
        ///abc: m r1, 0x20	;world!
        ///	l a2
        ///	; comment
        ///	1 067 0b111000111
        ///	
        ///	if a + 4 &lt;= 2 {
        ///	}
        ///
        ///	123abc	
        ///	123
        ///	;
        ///	@
        ///	1234
        ///	
        ///	; comparison
        ///	
        ///	!
        ///	abc
        ///	=
        ///	def
        /// != &quot;hello,\n world&quot;
        ///.
        /// </summary>
        internal static string TokenStreamNextTest {
            get {
                return ResourceManager.GetString("TokenStreamNextTest", resourceCulture);
            }
        }
    }
}
